server:
  port: 9999
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?charset=utf8mb4&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  flyway:
    enabled: true
    baseline-on-migrate: true
  elasticsearch:
    jest:
      uris: http://localhost:9200
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: localhost:9300
logging:
  level:
    # 全局等级
    root: warn
    com:
      sleepy: info